#!/bin/bash

# Developer:  🆁🅾🅱🅴🆁🆃🅾  🅲🅰🅻🅰🅱🆁🅴🆂🅴
# City:       🅿🅰🅻🅴🆁🅼🅾, 🆂🅸🅲🅸🅻🆈
# Country:    🅸🆃🅰🅻🆈

# Set the number of cores to use for the build.
#
# Note:  If set to `nproc` the script will use all available cores.
#
# Note:  Modify this value accordingly to your needs.
#NUMJOBS="8"
NUMJOBS=`nproc`

# Set the compile folder.
#
# Note:  The tclkits generated by the script will be located at:
#            "$OUTROOTDIR/Linux/x64/Release/Distribution/opt/Tcl/bin" for 64 bit system
#            "$OUTROOTDIR/Linux/x86/Release/Distribution/opt/Tcl/bin" for 32 bit system
#
# Note:  Modify this path accordingly to your needs.
OUTROOTDIR="build"

# Set the tcl or tclkit path.
#
# Note:  They must be at least 8.6.6 in order to run Bawt.
#
# Note:  You can install tcl through your distro package manager, for example:
#          Archlinux:     pacman -S tcl
#          Debian/Ubuntu: apt install tcl
#          Fedora:        dnf install tcl
#          Opensuse:      zypper install tcl
#
# Note:  Modify this path accordingly with your tcl or tclkit location.
TCLSH="/usr/bin/tclsh"

# Check the architecture type on the current build system.
ARCH=`uname -m`
if [[ "${ARCH}" == "x86_64" || "${ARCH}" == "amd64" || "${ARCH}" == "arm64" || "${ARCH}" == "aarch64" ]]; then
    ARCH="x64"
else
    ARCH="x86"
fi

# Check the tcl version to use.
if [ "$1" == "" ]; then
    echo
    echo "Usage: ./linux.sh TclTk"
    echo
    echo "  Where:"
    echo
    echo "    TclTk:  8.6.6  --> Tcl/Tk 8.6.6"
    echo "            8.6.7  --> Tcl/Tk 8.6.7"
    echo "            8.6.8  --> Tcl/Tk 8.6.8"
    echo "            8.6.9  --> Tcl/Tk 8.6.9"
    echo "            8.6.10 --> Tcl/Tk 8.6.10"
    echo "            8.6.11 --> Tcl/Tk 8.6.11"
    echo "            8.6.12 --> Tcl/Tk 8.6.12"
    echo "            8.6.13 --> Tcl/Tk 8.6.13"
    echo "            8.7.a5 --> Tcl/Tk 8.7.a5"
    echo "            8.7.b1 --> Tcl/Tk 8.7.b1"
    echo
    echo "Examples:"
    echo
    echo "  ./linux.sh 8.6.6  --> --> Will create tclkits that includes Tcl 8.6.6  (with and without Tk 8.6.6)"
    echo "  ./linux.sh 8.6.7  --> --> Will create tclkits that includes Tcl 8.6.7  (with and without Tk 8.6.7)"
    echo "  ..."
    echo "  ./linux.sh 8.7.a5 --> --> Will create tclkits that includes Tcl 8.7.a5 (with and without Tk 8.7.a5)"
    echo "  ./linux.sh 8.7.b1 --> --> Will create tclkits that includes Tcl 8.7.b1 (with and without Tk 8.7.b1)"
    echo
    echo "Note:  The tclkits architecture will be the same of the operative system in which it was build."
    echo "       If the operative system is at 64 bits, then the tclkits builded in it will be at 64 bits,"
    echo "       if it's at 32 bits, then the tclkits builded in it will be at 32 bits."
    exit 0
else
    TCL_VERSION="$1"
fi

# Consume the variable '$1'.
shift

# Build all libraries as listed in the setup file provided.
BAWTOPTS="--rootdir ${OUTROOTDIR} \
          --architecture ${ARCH} \
          --numjobs ${NUMJOBS} \
          --tclversion ${TCL_VERSION} \
          --tkversion ${TCL_VERSION}"

${TCLSH} assets/Bawt.tcl ${BAWTOPTS} --update assets/setup/tclkit1.0.bawt all

exit 0
